name: PR
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install NPM dependencies, cache node-modules and Cypress correctly
      # https://github.com/cypress-io/github-action
      - name: Install dependencies
        uses: cypress-io/github-action@v5.0.8
        with:
          runTests: false

  lint:
    needs: install-dependencies
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: cypress-io/github-action@v5.0.8
        with:
          runTests: false
      - name: lint
        run: yarn lint

  cypress-e2e-test:
    # if you want to enable parallelization
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v5.0.8
        with:
          # install: false # Cypress gha will take care of install instead of bahmutov/installs
          start: yarn start
          wait-on: 'http://localhost:8080'
          config-file: cypress/config/local.config.js
          browser: chrome
          # if you want to enable parallelization
          record: true
          parallel: true
          group: local-e2e-tests
          tag: local-e2e-tests
        env:
          # if you want to enable parallelization
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-ct-test:
    # if you want to enable parallelization
    # strategy:
    #   matrix:
    #     machines: [1, 2, 3]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress component tests 🧪
        uses: cypress-io/github-action@v5.0.8
        with:
          # we have already installed everything
          # install: false # Cypress gha will take care of caching instead of bahmutov/installs
          component: true
          browser: chrome
          # if you want to enable parallelization
          record: true
          parallel: false
          group: ct-tests
          tag: ct-tests
        env:
          # if you want to enable parallelization
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
